spring:
  cloud:
    gateway:
      routes:
        - id: r1
          # uri: http://localhost:8088/
          uri: http://microservice-client:8088/
          predicates:
            - Path=/clients/**
        - id: r2
          # uri: http://localhost:8089/
          uri: http://microservice-voiture:8089/
          predicates:
            - Path=/voitures/**
